#!/bin/sh
###############################################################################
# @(#) AWS EC2 Smart Snapshot
#
# MIT License
#
# Copyright (c) 2016 Tats Shibata
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
###############################################################################

trap 'myexit 1' 1 2 3 15

# {{{ myexit() {

myexit() {
  unfreeze_device
  exit $1
}

# }}}
# {{{ log()

log() {
  local pri=$1
  local msg=$2

  if [ $pri == NOTICE ]; then
    echo "`LANG=C date '+%b %e %T'` [$pri] $msg"
  else
    echo "`LANG=C date '+%b %e %T'` [$pri] $msg" >&2
  fi
}

# }}}
# {{{ obtain_volume_ids()

obtain_volume_ids() {
  local my_instance_id=`GET http://169.254.169.254/latest/meta-data/instance-id`

  volume_ids=`aws ec2 describe-volumes \
    --filters \
      Name=attachment.instance-id,Values=$my_instance_id \
      Name=tag-key,Values="Need Auto-Snapshot" \
      Name=tag-value,Values=yes \
    --query "Volumes[*].[VolumeId]" \
    --output text`

  local retval=$?

  if [ $retval != 0 ]; then
    log ERROR  "Can't obtain VolumeId [CODE=$retval]"
    myexit $retval
  fi
}

# }}}
# {{{ create_snapshot()

create_snapshot() {
  local hostname=`hostname`

  for volume_id in $volume_ids; do
    local device=`aws ec2 describe-volumes \
      --filters Name=volume-id,Values=$volume_id \
      --query "Volumes[*].Attachments[*].[Device]" \
      --output text`

    local retval=$?

    if [ $retval != 0 ]; then
      log ERROR  "Can't obtain Device [CODE=$retval]"
      myexit $retval
    fi

    freeze_device

    log NOTICE "Taking a snapshot..."

    local snapshot_id=`aws ec2 create-snapshot \
      --volume-id $volume_id \
      --description "Created by aws-ec2-smart-snapshot($hostname) from $volume_id($device)" \
      --query "[SnapshotId]" \
      --output text`

    local retval=$?

    if [ $retval != 0 ]; then
      log ERROR  "Failed to take a snapshot [CODE=$retval]"
      myexit $retval
    fi

    unfreeze_device

    aws ec2 create-tags \
      --resources $snapshot_id \
      --tags \
        Key=Name,Value="$hostname $device" \
        Key=CreatedBy,Value=aws-ec2-smart-snapshot

    local retval=$?

    if [ $retval != 0 ]; then
      log ERROR  "Failed to add tags [CODE=$retval]"
      myexit $retval
    fi
  done
}

# }}}
# {{{ purge_old()

purge_old() {
  for volume_id in $volume_ids; do
    aws ec2 describe-snapshots \
      --filters Name=volume-id,Values=$volume_id \
      --query 'Snapshots[*].[StartTime,SnapshotId]' \
      --output text > /tmp/snapshots.lst

    local retval=$?

    if [ $retval != 0 ]; then
      log ERROR  "Can't obtain SnapshotId [CODE=$retval]"
      myexit $retval
    fi

    local num_keeped=`aws ec2 describe-tags \
      --filters \
        Name=resource-id,Values=$volume_id \
        Name=key,Values="# Auto-Snapshot" \
      --query 'Tags[*].[Value]' \
      --output text`

    local retval=$?

    if [ $retval != 0 ]; then
      log ERROR  "Can't obtain # of Auto-Snapshot [CODE=$retval]"
      myexit $retval
    fi

    if [ "$num_keeped" == "" ]; then
      local num_keeped=90
    fi

    local num_rows=`cat /tmp/snapshots.lst | wc -l`
    local num_deleted=`expr $num_rows - $num_keeped`

    if [ $num_deleted -le 0 ]; then
      return
    fi

    local deleted_snapshots=`cat /tmp/snapshots.lst | sort | head -n $num_deleted | awk '{print $2}'`

    for deleted_snapshot in $deleted_snapshots; do
      log NOTICE "Delete a snapshot $deleted_snapshot"
      aws ec2 delete-snapshot --snapshot-id $deleted_snapshot

      local retval=$?

      if [ $retval != 0 ]; then
        log ERROR  "Failed to delete the snapshot [CODE=$retval]"
        myexit $retval
      fi
    done
  done

  rm -f /tmp/snapshots.lst
}

# }}}
# {{{ freeze_device()

freeze_device() {
  local virt_device=`echo $device | sed 's!/dev/sd!/dev/xvd!'`
  mount_paths=`grep $virt_device /etc/fstab | awk '{print $2}'`

  if [ "$mount_paths" == "" ]; then
    local vg_name=`pvs | grep $virt_device | awk '{print $2}'`
    mount_paths=`grep $vg_name /etc/fstab | awk '{print $2}'`
  fi

  if [ "$mount_paths" == "" ]; then
    log WARNING "Can't obtain the paths $device mounting"
  fi

  for mount_path in $mount_paths; do
    log NOTICE "Freezing $mount_path..."
    xfs_freeze -f $mount_path
  done
}

# }}}
# {{{ unfreeze_device()

unfreeze_device() {
  for mount_path in $mount_paths; do
    log NOTICE "Unfreezing $mount_path..."
    xfs_freeze -u $mount_path
  done
}

# }}}
# {{{ Main

obtain_volume_ids

create_snapshot

# TODO: purge_excess

purge_old

# }}}
